epc = read.table("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?")
dt <- paste(epc$Date, epc$Time)
epc$datetime <- strptime(dt, "%d/%m/%Y %H:%M:%S")
epc$Date <- as.Date(epc$Date, "%d/%m/%Y")
epc2days <- subset(epc, epc$Date=="2007-02-01"|epc$Date=="2007-02-02")
png(filename = "plot4.png")
par(mfcol = c(2,2))
with(epc2days, plot(datetime, Global_active_power, ylab = "Global Active Power (kilowatts)", type = "l", xlab = ""))
{with(epc2days, plot(datetime, Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = ""))
   with(epc2days, lines(datetime, Sub_metering_2, col = "red"))
   with(epc2days, lines(datetime, Sub_metering_3, col = "blue"))
   legend("topright", lty = 1, cex = 0.3, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), xjust = 1)
}
with(epc2days, plot(datetime, Voltage, type = "l"))
with(epc2days, plot(datetime, Global_reactive_power, type = "l"))
dev.off()